### PR TITLE
warrior: add arms core auras

### PR DESCRIPTION
**Pull request by dafzor**
Some of the Arms spell auras, missing Fury and Protection.

### CODE REVIEW

**Comment by Rainrider** [comment]
Welcome back @dafzor and thank you for the PR. Would you mind changing the commit message to `warrior: add arms core abilities` or something like that? The format should be like `<class>: <add|update|fix|remove> <spec> <core|talents|honor talents|artifact>...`

**Comment by dafzor** [comment]
Thanks, having been playing for over a year now. I can't seem to figure out how to change the commit message from the website UI. Is it even possible?

**Comment by Rainrider** [comment]
See [here](https://help.github.com/articles/changing-a-commit-message/). If you have made further changes to the same branch, commit them first and rebase (or stash them and reapply the stash after ammending the commit). As you rewrite history, you'll have to force push the branch. The PR here will update automatically.

**Comment by dafzor** [comment]
I've just been using the website edit function to apply my changes. I'll get a git client and fix it as soon as i can.

**Comment by dafzor** [comment]
In the spirit of getting it done I just used the website to do a new pull request with proper message and trying to close this one so it's ignored.

**Pull request closed without merging**
