### PR TITLE
Battle for Azeroth Paladin

### PR DESCRIPTION
**Pull request by VaporAPX**
Base BFA protection paladin abilities (all tested)

### CODE REVIEW

**Comment by Rainrider** [comment]
Cool, I hope you didn't have too much trouble setting the whole thing up. Looking good so far, I just have some remarks if you don't mind:

1. The interface should be `80000` and not `80100` (see https://github.com/AdiAddons/LibPlayerSpells-1.0/wiki/Contribution-Guidelines#editing-the-spell-lists)
2. Could you please add the spec name to the comments where it is applicable, like `53595, -- Hammer of the Righteous (Protection)`? This is helpful when reviewing the data later.
3. Some of the indentation is not correct. You don't have to increase the indentation level for nested lists.
Instead of
```lua
PERSONAL = {
	188370, -- Consecration (Protection)
	276112, -- Divine Steed
		BURST = {
			31884, -- Avenging Wrath
		},
		SURVIVAL = {
			642,    -- Divine Shield
			31850,  -- Ardent Defender
			86659,  -- Guardian of Ancient Kings
			132403, -- Shield of the Righteous
		},
},
```  
you should
```lua
PERSONAL = {
	188370, -- Consecration (Protection)
	276112, -- Divine Steed
	BURST = {
		31884, -- Avenging Wrath
	},
	SURVIVAL = {
		642,    -- Divine Shield
		31850,  -- Ardent Defender
		86659,  -- Guardian of Ancient Kings
		132403, -- Shield of the Righteous
	},
},
```  
Proper indentation will spare you some mistakes in the future
4. Aligning the numbers to the right would be nice too as it improves readability (see the example in https://github.com/AdiAddons/LibPlayerSpells-1.0/wiki/Contribution-Guidelines#comments)

I can also change those later before merging, but it will be helpful to you if you do it before the spell list gets bigger.

Thanks a ton for you help, much appreciated!

**Comment by VaporAPX** [comment]
I thought that since the current beta version is 8.0.1 that the version here should reflect as 80100, my mistake. The indentation and right alignment I actually changed to make it easier for me to read lol.  I can change it back, no worries.  Thanks for the help, any more insight along the way by all means keep letting me know.

**Comment by Rainrider** [comment]
Thanks a lot for helping out!

The indentation is still not quite right, but I can adjust that when you are done, so no worries.

> Removed "bad" border for consecration for protection, more beneficial to spec to have "good" border showing as buff.

The "good" and "bad" borders are a concept of ABA not of LPS. It should be up to the consuming addon to decide whether it should show the self-buff or the debuff or delegate this decision to the end user (like ABA does). You should list "Consecrate" both as a self-buff (like you already did) and a debuff (id: 204242). ABA users can then choose to disable either or all of the generated rules. We can also exclude the debuff in ABA when calling `LPS:ImportPlayerSpells` as you are right that the debuff is of little value to a protection paladin.

- "Avenger's Shield" should be listed as an interrupt too.
- "Light of the Protector" should be listed as a cooldown.
- "Divine Steed" has different buff ids depending on player's racial mount.
  - 276111 dwarf
  - 266112 dark iron dwarf
  - 221887 draenei/lightforged draenei
  - ...
- "Rebuke" has a wrong spell id - the right one is 96231
- "Bastion of Light" should be listed as a cooldown
- "Blessing of Spellwarding" also causes "Forbearance"
- "Final Stand" (204079) should be under CROWD_CTR - TAUNT
- Final Stand's provider is 204077, and the modified spell is "Divine Shield" (642). "Hand of Reckoning" is wrong here, It's the job of the display addon to group taunts together.
- "Hand of the Protector" should be listed as a cooldown
- The provider for "Judgement of Light" is 183778, the modified spell is "Judgement" (275779)
- "Aegis of Light" also applies 204335 on allies.

The reason to add the talents as providers for "Final Stand" and "Judgement of Light" is that the rules for them should only be active when the talents are selected by the player.

Don't have any more time to test honor talents and retribution. Will look into them these days.

**Comment by VaporAPX** [comment]
I keep forgetting that this is the library being updated and not ABA specifically, and that other addons will use it as well.  Guess I've still got some learning to do, hopefully improve as I go along.  You sure you still want me helping? lol

The indentation doesn't copy over nicely from notepad++ where I do most of my editing and testing in game.  Maybe it's a bad habit copying from notepad to here but I'm not fluent enough in this, I need to constantly test any changes I make in game.

I'll get these errors tuned up, and try and remember I'm editing a library not ABA.

**Comment by Rainrider** [comment]
Come over in https://gitter.im/AdiAddons/LibPlayerSpells-1.0 or text me on private through gitter.im if you'd prefer that. You can login with your github accound. I might be able to help setting the whole thing up :)

**Comment by Rainrider** [comment]
Just a condensed example of how to properly list "Final Stand" and "Judgement of Light"
```lua
lib:__RegisterSpells('PALADIN', 80000, 1, {
	COOLDOWN = {
		AURA = {
			HARMFUL = {
				196941, -- Judgement of Light (Protection talent)
				CROWD_CTRL = {
					TAUNT = {
						 62124, -- Hand of Reckoning
						204079, -- Final Stand (Protection talent)
					},
				},
			},
		},
	},
}, {
	-- map aura to provider(s)
	[196941] = 183778, -- Judgement of Light (Protection talent)
	[204079] = 204077, -- Final Stand (Protection talent)
}, {
	-- map aura to modified spell(s)
	[196941] = 275779, -- Judgement of Light (Protection talent) -> Judgement
	[204079] =    642, -- Final Stand (Protection talent) -> Divine Shield
})
```
Maybe a diff makes it more visible:
```diff
diff --git a/data/Paladin.lua b/data/Paladin.lua
index c5892b2..32e960c 100644
--- a/data/Paladin.lua
+++ b/data/Paladin.lua
@@ -1,17 +1,21 @@
 --[[
 LibPlayerSpells-1.0 - Additional information about player spells.
 (c) 2013-2014 Adirelle (adirelle@gmail.com)
+
 This file is part of LibPlayerSpells-1.0.
+
 LibPlayerSpells-1.0 is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
+
 LibPlayerSpells-1.0 is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
+
 You should have received a copy of the GNU General Public License
-along with LibPlayerSpells-1.0.  If not, see <http://www.gnu.org/licenses/>.
+along with LibPlayerSpells-1.0. If not, see <http://www.gnu.org/licenses/>.
 --]]
 
 local lib = LibStub("LibPlayerSpells-1.0")
@@ -26,11 +30,10 @@ lib:__RegisterSpells("PALADIN", 80000, 1, {
 		184575, -- Blade of Justice (Retribution)
 		204035, -- Bastion of Light (Protection Talent)
 		210191, -- Word of Glory (Retribution Talent)
-		213652, -- Hand of the Protector (Protection Talent)		 
+		213652, -- Hand of the Protector (Protection Talent)
 		275779, -- Judgement (Protection)
 		INTERRUPT = {
 			96231, -- Rebuke
-			31935, -- Avenger's Shield (Protection)
 		},
 		DISPEL = {
 			HELPFUL = {
@@ -40,31 +43,34 @@ lib:__RegisterSpells("PALADIN", 80000, 1, {
 		},
 		AURA = {
 			HELPFUL = {
-			          1044, -- Blessing of Freedom
-				204335, -- Aegis of Light (Protection Talent)
-				[25771] = "INVERT_AURA", -- Forbearance	
-				204018, -- Blessing of Spellwarding (Protection Talent)
+				   1044, -- Blessing of Freedom
+				 204018, -- Blessing of Spellwarding (Protection Talent)
+				 204335, -- Aegis of Light (Protection Talent)
+				[ 25771] = "INVERT_AURA", -- Forbearance	
 				SURVIVAL = {
 					1022, -- Blessing of Protection
 					6940, -- Blessing of Sacrifice
 				},
 			},
 			HARMFUL = {
-				  31935, -- Avenger's Shield (Protection)
 				 196941, -- Judgement of Light (Protection Talent)
 				 197277, -- Judgement (Retribution)
 				 204242, -- Consecration (Protection)
-				 204079, -- Final Stand (Protection Talent / Taunt)
 				 204301, -- Blessed Hammer (Protection Talent)
+				 267799, -- Execution Sentence (Retribution)
+				[ 31935] = 'INTERRUPT', -- Avenger's Shield (Protection)
 				[206891] = "UNIQUE_AURA", -- Inquisition (Protection PvP Talent)
-			     	 267799, -- Execution Sentence (Retribution)
 				CROWD_CTRL = {
-					   [853] = "STUN", -- Hammer of Justice
-					 [20066] = "INCAPACITATE", -- Repentance 
-					 [62124] = "TAUNT", -- Hand of Reckoning
+					[ 20066] = "INCAPACITATE", -- Repentance 
 					[105421] = "DISORIENT", -- Blinding Light
-					[204079] = "TAUNT", -- Final Stand (Protection Talent)
-					[205290] = "STUN", -- Wake of Ashes (Retribution Talent)
+					STUN = {
+						   853, -- Hammer of Justice
+						205290, -- Wake of Ashes (Retribution Talent)
+					},
+					TAUNT = {
+						 62124, -- Hand of Reckoning
+						204079, -- Final Stand (Protection Talent)
+					}
 				},
 				SNARE = {
 					183218, -- Hand of Hindrance (Retribution)
@@ -87,8 +93,8 @@ lib:__RegisterSpells("PALADIN", 80000, 1, {
 					 86659, -- Guardian of Ancient Kings
 					132403, -- Shield of the Righteous (Protection)
 					184662, -- Shield of Vengeance (Retribution)
-				    	204150, -- Aegis of Light (Protection Talent)
-				    	205191, -- Eye for an Eye (Retribution Talent)
+					204150, -- Aegis of Light (Protection Talent)
+					205191, -- Eye for an Eye (Retribution Talent)
 				},
 			},
 		},
@@ -105,35 +111,36 @@ lib:__RegisterSpells("PALADIN", 80000, 1, {
 	},
 },  {
 	-- Map Aura to Provider(s)
+	[ 25771] = { -- Forbearance
+		   633, -- Lay on Hands
+		   642, -- Divine Shield
+		  1022, -- Blessing of Protection
+		204018, -- Blessing of Spellwarding
+	},
 	[105421] = 115750, -- Blinding Light (Disorient / Protection Talent)
-	[114250] = 19750, -- Selfless Healer (Retribution Talent)
-	[132403] = 53600, -- Shield of the Righteous (Protection)
-	[188370] = 26573, -- Consecration (Protection)
+	[114250] =  19750, -- Selfless Healer (Retribution Talent)
+	[132403] =  53600, -- Shield of the Righteous (Protection)
+	[188370] =  26573, -- Consecration (Protection)
 	[196941] = 275779, -- Judgement of Light (Protection Talent)
-	[197277] = 20271, -- Judgement (Retribution)
-	[204242] = 26573, -- Consecration (Protection)
-	[204077] = 642, -- Final Stand to Divine Shield (Taunt / Protection Talent)
+	[197277] =  20271, -- Judgement (Retribution)
+	[204079] = 204077, -- Final Stand (Protection Talent)
+	[204242] =  26573, -- Consecration (Protection)
 	[204301] = 204019, -- Blessed Hammer (Protection Talent)
 	[204335] = 204150, -- Aegis of Light (Protection Talent)
 	[206891] = 207028, -- Intimidated to Inquisition (Protection Honor Talent / Taunt)
 	[223819] = 223817, -- Divine Purpose (Retribution Talent)
-	[25771] = { -- Forbearance
-		   633, -- Lay on Hands
-		   642, -- Divine Shield
-	      	  1022, -- Blessing of Protection
-		204018, -- Blessing of Spellwarding
-	},
-	[267611] = 85256, -- Righteous Verdict (Retribution Talent)
+	[267611] =  85256, -- Righteous Verdict (Retribution Talent)
 	[267799] = 267798, -- Execution Sentence (Retribution Talent)
 	[276112] = 190784, -- Divine Steed
 }, {
 	-- Map Aura to Modified Spell(s)
 	[183778] = 275779, -- Judgement of Light (Protection Talent)
+	[204079] =    642, -- Final Stand to Divine Shield (Protection Talent)
 	[223819] = { -- Divine Purpose (Retribution)
 		 53385, -- Divine Storm
 		 85256, -- Templar's Verdict
 		210191, -- Word of Glory
-		267798, -- Execution Sentence
 		215661, -- Justicar's Vengeance
+		267798, -- Execution Sentence
 	},
 })
```
This diff includes indentation, spell ordering, number alignment and the other fixes.

I think you still apply all this through Github's web interface. Maybe the reason you don't get the indentation is that it does not use a monospaced font so it is hard to see how they should align. Don't bother with indentation, I can fix it later.

Thank you again for taking the time with all this.

**Comment by Rainrider** [comment]
No worries, it will all come into place :)

Btw with git you could just use `git appy file_with_diff_copied_from_above.diff` to apply the changes. If you come to gitter.im, I can help you set it up. It shouldn't take more than 10 mins and it is something you could use for other projects too.

**Comment by Rainrider** [comment]
Thank you for the last commits. Don't bother with Honor talents for now, they are a bit tricky to add, I'll have to re-add support for them in LibSpellbook and make changes to DebugTooltip in ABA.

If you are done with the rest, I will try to review later today and apply changes myself. I can do it directly in your branch if you provide persmssions for that (see https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) or I'll just merge and apply them in another topic branch.

Thanks again for you help

**Comment by VaporAPX** [comment]
I was just now going through the PvP talents, since I actually didn't know there's a PvP target dummy that enables them right in Stormwind.  Who knew?  But I'm finding it tricky as you've mentioned so I'll move on for now.  I just need to make one more addition that I keep forgetting and that's to add the divine steed ID's for the other classes.  3 commits later and I forgot to put them in every time.  You can modify mine for sure, I've enabled access.  Whatever is easiest for you.

**Comment by Rainrider** [comment]
The problem with the honor talents is how to get the providers - some of them appear in the spell book when active, some don't. I can use `GetPvpTalentInfoByID` to get the actual spell id, but I saw cases where it does not correspond to what's added to the spell book (I think only for passive spells, but not sure right now). The pvp dummy in SW is an issue in itself. Honor talents deactivate themselves randomly even when you are in combat with it.

Thanks for enabling access, this would be the easiest for me but I hope it does not break your workflow as it will introduce changes you don't have locally and if you have changes that you have not committed yet, it might overwrite them when you pull them in. Those are easy to spot and solve normally but I'm not sure how you do it with Github's web interface. Basically if you have committed all your pending changes, there should be nothing to worry about.

**Comment by VaporAPX** [comment]
Everything that I've committed on here is current to my own copy.  I went back in and removed the pvp related stuff I was starting to add after you mentioned it.  I just started putting warrior abilities together when my night shift ended, but that's where I'm looking to go next.

**Comment by Rainrider** [comment]
@VaporAPX I'm finished with the paladin spells. I also added [some paladin rules for ABA](https://github.com/AdiAddons/AdiButtonAuras/pull/279). It would be cool if you could test if I forgot something or did something wrong.

**Comment by VaporAPX** [comment]
I'll give it a go tonight, plan on adding more warrior stuff this evening as well after I get home from work.

Sorry for making you clean so much up, hoping warrior isn't so bad for you lol

**Comment by Rainrider** [comment]
No worries :) The tidy up commit looks like more than it actually is (and that's me having CDO - that is [OCD](https://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_disorder) with the letters sorted alphabetically :)). Prot and Ret talents were the only thing that was not that good but that was before we talked about it and Holy was fine, so I see you know how to do it now. I appreciate you help, be sure about that.

The only thing that remains is you actually using git rather than Github's web interface as this will imho simplify and speed up your workflow. But this is up to you (you can still talk to me on gitter.im) :)

**Comment by Rainrider** [comment]
@VaporAPX did you get a chance to test the changes?

If not, could you also please checkout the bfa branch of AdiButtonAuras while testing. I introduced some changes there and want to be sure there are no side effects.

**Pull request merged**
