### PR TITLE
Shadowlands

### PR DESCRIPTION
**Pull request by Rainrider**
If you want to contribute to class data, please post in the discussion and open a separate pull request with the `shadowlands` branch as base. Please take note of the [contribution guidelines](https://github.com/AdiAddons/LibPlayerSpells-1.0/wiki/Contribution-Guidelines).

Classes
--------
- [ ] Death Knight
  - [ ] base
  - [ ] Blood
    - [ ] talents
    - [ ] honor talents
  - [ ] Frost
    - [ ] talents
    - [ ] honor talents
  - [ ] Unholy
    - [ ] talents
    - [ ] honor talents
- [x] Demon Hunter (Rainrider)
  - [x] base
  - [x] Havoc
    - [x] talents
    - [x] honor talents
  - [x] Vengeance
    - [x] talents
    - [x] honor talents
- [ ] Druid
  - [ ] base
  - [ ] Balance
    - [ ] talents
    - [ ] honor talents
  - [ ] Feral
    - [ ] talents
    - [ ] honor talents
  - [ ] Guardian
    - [ ] talents
    - [ ] honor talents
  - [ ] Restoration
    - [ ] talents
    - [ ] honor talents
- [ ] Hunter
  - [ ] base
  - [ ] Beast Mastery
    - [ ] talents
    - [ ] honor talents
  - [ ] Marksmanship
    - [ ] talents
    - [ ] honor talents
  - [ ] Survival
    - [ ] talents
    - [ ] honor talents
  - [ ] Pets
- [ ] Mage
  - [ ] base
  - [ ] Arcane
    - [ ] talents
    - [ ] honor talents
  - [ ] Fire
    - [ ] talents
    - [ ] honor talents
  - [ ] Frost
    - [ ] talents
    - [ ] honor talents
- [ ] Monk
  - [ ] base
  - [ ] Brewmaster
    - [ ] talents
    - [ ] honor talents
  - [ ] Mistweaver
    - [ ] talents
    - [ ] honor talents
  - [ ] Windwalker
    - [ ] talents
    - [ ] honor talents
- [ ] Paladin
  - [ ] base
  - [ ] Holy
    - [ ] talents
    - [ ] honor talents
  - [ ] Protection
    - [ ] talents
    - [ ] honor talents
  - [ ] Retribution
    - [ ] talents
    - [ ] honor talents
- [ ] Priest
  - [ ] base
  - [ ] Discipline
    - [ ] talents
    - [ ] honor talents
  - [ ] Holy
    - [ ] talents
    - [ ] honor talents
  - [ ] Shadow
    - [ ] talents
    - [ ] honor talents
- [ ] Rogue
  - [ ] base
  - [ ] Assassination
    - [ ] talents
    - [ ] honor talents
  - [ ] Outlaw
    - [ ] talents
    - [ ] honor talents
  - [ ] Subtlety
    - [ ] talents
    - [ ] honor talents
- [ ] Shaman
  - [ ] base
  - [ ] Elemental
    - [ ] talents
    - [ ] honor talents
  - [ ] Enhancement
    - [ ] talents
    - [ ] honor talents
  - [ ] Restoration
    - [ ] talents
    - [ ] honor talents
- [ ] Warlock
  - [ ] base
  - [ ] Affliction
    - [ ] talents
    - [ ] honor talents
  - [ ] Demonology
    - [ ] talents
    - [ ] honor talents
  - [ ] Destruction
    - [ ] talents
    - [ ] honor talents
- [ ] Warrior
  - [ ] base
  - [ ] Arms
    - [ ] talents
    - [ ] honor talents
  - [ ] Fury
    - [ ] talents
    - [ ] honor talents
  - [ ] Protection
    - [ ] talents
    - [ ] honor talents

### CODE REVIEW

**Comment by arcadepro** [comment]
What are we doing with conduits? Just add them into LibPlayerSpells as if they're talents? (Working on Warrior atm)

**Comment by Rainrider** [comment]
Conduits are detected by LibSpellbook and can be used as required spells in custom rules. I don't plan on adding them to LibPlayerSpells as expansion stuff like that is normally subject to common iteration and thus time consuming to keep up to date.

I also don't plan on updating LibPlayerSpells myself, please contribute if you don't want stale data for your class.

**Comment by arcadepro** [comment]
I assume the same goes for Legendary item effects?

**Comment by Rainrider** [comment]
Legendary items won't be covered at all. LibItemBuffs is broken because of changes in wowhead (where we pulled item buffs data from). You should still be able to create custom rules for those though.

**Comment by Rainrider** [comment]
@arcadepro any progress on warrior you might want to share? I would like to merge this into master and release the new ABA version like in the next hour or so.

**Pull request merged**
