### PR TITLE
mage: add arcane core and talents up to level 60

### PR DESCRIPTION
**Pull request by dafzor**
Only gotten to level 70, will add the rest as I go. One of the abilities (Mirror Image) does not show an aura so while in the list it's "untracked".

### CODE REVIEW

**Comment by dafzor** [comment]
Why did it fail?

**Comment by Rainrider** [comment]
The platform we use for testing updated their luaunit version to one the tests do not support. Adirelle is on it. Don't worry about it.

**Comment by dafzor** [comment]
Do i need to resubmit the pull request for it to be reevaluated?

**Comment by Rainrider** [comment]
Have you read https://github.com/AdiAddons/LibPlayerSpells-1.0/issues/82#issuecomment-234800725? Slows, snares and dazes are not considered crowd control.

You don't have to resubmit, just push further changes to the same branch. I still don't know if this is possible through the web interface as you haven't answered https://github.com/AdiAddons/LibPlayerSpells-1.0/pull/93#issuecomment-234716332 yet.

**Comment by dafzor** [comment]
@Rainrider yes I can, it lets me edit as a further commit on the branch and I already have, I let some fixes I had already made slip in as well which I hope is okay.

**Comment by Rainrider** [comment]
I'll take a look tomorrow.

**Pull request merged**
